---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/ipvzero/N3/hosts.yaml"
        group_file: "/home/ipvzero/N3/groups.yaml"
        defaults_file: "/home/ipvzero/N3/defaults.yaml"

runners:
    plugin: threaded
    options:
        num_workers: 10
